name: CI
on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v2.5.1
        with:
          node-versions: "14.X"
        
        
      - name: install && build
        run: yarn && yarn docs:build

      - name: deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: 'docs/.vuepress/dist/'
          target: '/usr/share/nginx/html/press'
          strip_components: 1